import pandas as pd

df1 = pd.read_csv(r"D:\DataAnalytics\DataAnalyticsProject\Public_Transport\routes_with_coordinates.csv")
print(df1.shape)
print(df1.isnull().sum())
df1 = df1.drop(columns= ['latitude','longitude'])
print("DF1","\n",df1.head())

df2 = pd.read_csv(r"D:\DataAnalytics\DataAnalyticsProject\Public_Transport\routes.csv")
print(df2.shape)
print(df2.isnull().sum())
print(df2.head())
df2 = df2.drop(columns=["route_desc","route_url"])
print(df2.head())
print(df2["agency_id"].value_counts())
print(df2["route_color"].value_counts())
print(df2["route_text_color"].value_counts())
print(df2["route_type"].value_counts())
df2 = df2.drop(columns=["agency_id","route_color","route_text_color","route_type"])
print("DF2","\n",df2.head())

df3 = pd.read_csv(r"D:\DataAnalytics\DataAnalyticsProject\Public_Transport\stop_times.csv")
print(df3.shape)
print(df3.head())
print(df3.isnull().sum())
df3 = df3.drop(columns=["shape_dist_traveled","stop_headsign"])
print(df3.head())
print(df3["drop_off_type"].value_counts())
print(df3["pickup_type"].value_counts())
print(df3["stop_id"].value_counts())
print(df3["stop_sequence"].value_counts())
print(df3["timepoint"].value_counts())
df3 = df3.drop(columns=["drop_off_type","pickup_type","timepoint"])
print("DF3","\n",df3.head())

df4 = pd.read_csv(r"D:\DataAnalytics\DataAnalyticsProject\Public_Transport\stops.csv",index_col=False)
print(df4.shape)
print(df4.head())
print(df4.isnull().sum())
df4 = df4.drop(columns=["location_type","parent_station","stop_code","stop_desc","stop_timezone","stop_url","wheelchair_boarding","zone_id"])
print("DF4","\n",df4.head())

df5 = pd.read_csv(r"D:\DataAnalytics\DataAnalyticsProject\Public_Transport\trips.csv", index_col=False)
print(df5.shape)
print(df5.head())
print(df5.isnull().sum())
df5 = df5.drop(columns=["bikes_allowed","block_id","shape_id","trip_headsign","trip_short_name","wheelchair_accessible"])
print("DF5","\n",df5.head())

busiest_routes = df5["route_id"].value_counts().head(10)
busiest_routes = busiest_routes.reset_index()
busiest_routes = pd.merge(busiest_routes,df2,on="route_id")
print("Busiest Routes","\n",busiest_routes)

busiest_stops = df3["stop_id"].value_counts().head(10)
busiest_stops=busiest_stops.reset_index()
busiest_stops=pd.merge(busiest_stops,df4, on= "stop_id")
busiest_stops=busiest_stops.drop(columns=["stop_lat","stop_lon"])
print("Busiest Stops","\n", busiest_stops)

df3["hour"] = df3["arrival_time"].str.split(':').str[0]
print(df3.head(10))
busiest_hours = df3["hour"].value_counts().head(10)
busiest_hours = busiest_hours.reset_index()
print("Busiest Hours","\n", busiest_hours)