import pandas as pd

df1 = pd.read_csv(r'D:\DataAnalytics\DataAnalyticsProject\Public_Transport\routes_with_coordinates.csv')
# print(df1.isnull().sum())
print(df1.head())
# routes.csv - load and clean
df2 = pd.read_csv(r'D:\DataAnalytics\DataAnalyticsProject\Public_Transport\routes.csv')
print(df2.isnull().sum())
df2 = df2.drop(columns=['route_desc', 'route_url'])
# print("routes.csv shape:", df2.shape)
print(df2.head())

# stops.csv - load and profile
df3 = pd.read_csv(r'D:\DataAnalytics\DataAnalyticsProject\Public_Transport\stops.csv')
print("stops.csv shape:", df3.shape)
# print(df3.columns.tolist())
# print(df3.isnull().sum())
# print(df3.head())
df3 = df3.drop(columns=['location_type', 'parent_station', 'stop_code', 'stop_name', 'stop_timezone', 'stop_url', 'wheelchair_boarding', 'zone_id'])
# print(df3.shape)
# print(df3.head())
# print(df3.dtypes)
# print(df3.iloc[0])
df3 = pd.read_csv(r'D:\DataAnalytics\DataAnalyticsProject\Public_Transport\stops.csv', index_col=False)
# print(df3.head())
df3 = df3[['stop_id', 'stop_name', 'stop_lat', 'stop_lon']]
print(df3.head())

df4 = pd.read_csv(r'D:\DataAnalytics\DataAnalyticsProject\Public_Transport\stop_times.csv', index_col=False)
# print(df4.shape)
# print(df4.columns.tolist())
# print(df4.isnull().sum())
# print(df4.head())
# print(df4['drop_off_type'].value_counts())
# print(df4['pickup_type'].value_counts())
# print(df4['timepoint'].value_counts())
# print(df4['stop_sequence'].value_counts())
df4 = df4.drop(columns=['shape_dist_traveled', 'stop_headsign', 'drop_off_type', 'pickup_type', 'timepoint'])
# print(df4.shape)
print(df4.head())

df5 = pd.read_csv(r'D:\DataAnalytics\DataAnalyticsProject\Public_Transport\trips.csv', index_col=False)
# print(df5.shape)
# print(df5.columns.tolist())
# print(df5.isnull().sum())
# print(df5.head())
df5 = df5.drop(columns=['bikes_allowed', 'block_id', 'shape_id', 'trip_headsign', 'trip_short_name', 'wheelchair_accessible'])
# print(df5.shape)
print(df5.head())

busiest_routes = df5['route_id'].value_counts().head(10)
print(busiest_routes)
busiest_routes_df = busiest_routes.reset_index()
print(busiest_routes_df)
result = pd.merge(busiest_routes_df, df2, on='route_id')
print(result)
result = result[['route_id', 'route_long_name', 'count']]
print(result)

result1 = pd.merge(df4,df5, on = 'trip_id') 
stop_seq_mean = result1.groupby('route_id')['stop_sequence'].mean()
print(stop_seq_mean)